name: build

on:
  push:
    branches:
      - '**/*'
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        postgres: [12, 13, 14, 15, 16, 17, 18]
    services:
      postgres:
        image: postgres:${{ matrix.postgres }}
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: floodit
          POSTGRES_USER: floodit
          POSTGRES_PASSWORD: floodit
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      # https://github.com/actions/checkout
      - name: Checkout the repository
        uses: actions/checkout@v5

      # https://github.com/asdf-vm/actions#setup
      - name: Install asdf
        uses: asdf-vm/actions/setup@v4
        with:
          asdf_version: 0.18.0

      - id: install-java
        name: Install Java with asdf
        run: |
          asdf plugin add java
          asdf install java
          which java
          java -version
          echo $JAVA_HOME

      - name: Show Maven version
        env:
          JAVA_HOME: ${{ steps.install-java.outputs.JAVA_HOME }}
        run: |
          which mvn
          mvn --version

      - name: Install Node.js with asdf
        run: |
          asdf plugin add nodejs
          asdf install nodejs
          which node
          node --version

      - name: Install backend dependencies
        env:
          JAVA_HOME: ${{ steps.install-java.outputs.JAVA_HOME }}
        run: |
          cd backend
          mvn --batch-mode dependency:resolve dependency:resolve-plugins initialize

      - name: Install frontend dependencies
        run: |
          npm ci

      - name: Check source code formatting
        run: |
          npm run format

      - name: Test the backend application
        env:
          FLOODIT_TEST_DATABASE_HOST: localhost
          FLOODIT_TEST_DATABASE_PORT: 5432
          FLOODIT_TEST_DATABASE_NAME: floodit
          FLOODIT_TEST_DATABASE_USERNAME: floodit
          FLOODIT_TEST_DATABASE_PASSWORD: floodit
          JAVA_HOME: ${{ steps.install-java.outputs.JAVA_HOME }}
        run: |
          cd backend
          mvn --batch-mode clean test

      - name: Build the backend application
        env:
          JAVA_HOME: ${{ steps.install-java.outputs.JAVA_HOME }}
        run: |
          cd backend
          mvn --batch-mode clean install -Pskip-test

      - name: Build the frontend application
        run: |
          npm run build

      - name: Ensure there are no uncommitted changes
        run: |
          git status --porcelain
          test -z "$(git status --porcelain)"
